#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     IR_Sensor,      sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     IR_Back,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          spinnerLeft,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          spinnerRight,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     linearRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    doorBack,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    doorFront,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    pullerLeft,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    pullerRight,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Util.h"
#include "Motor.h"
#include "Auto.h"
#include "IR.h"

void initializeRobot()
{
    disableDiagnosticsDisplay();

    servoChangeRate[pullerLeft] = 3;
    servoChangeRate[pullerRight] = 3;

    nMotorEncoder[backRight] = 0;

    startTask(Start_IR);

    eraseDisplay();
    autoRoutine = selectAutoRoutine();

    return;
}


// TODO: All this crap

// Red - Ramp
void  routineOne()
{
  eraseDisplay();
  nxtDisplayBigTextLine(0, "Three");

  Drive(70, 90);

};

// Red - Ground
void routineTwo()
{
    eraseDisplay();
    nxtDisplayBigTextLine(0, "Two");

    RetractGrabbers();
    Drive(12, 90);
};

// Blue - Ramp
void routineThree()
{
    eraseDisplay();
    nxtDisplayBigTextLine(0, "Three");

    Drive(70, 90);
    wait1Msec(500);

    if (FuzzyEquals(IR, 5, 1) && IR2 == 5)
    {
        Turn(-WHEEL_45_DEGREES * 1.5, 90);
        wait1Msec(500);
        Drive(-90, 90);
  	}

    wait1Msec(5000);
};

// Blue - Ground
void routineFour()
{
    while (1)
    {
        eraseDisplay();
        nxtDisplayBigTextLine(0, "Four");
    }
};

task main()
{
    initializeRobot();

    eraseDisplay();
    nxtDisplayBigTextLine(0, "Routine:");
    nxtDisplayBigTextLine(2, "%u", autoRoutine);

    waitForStart();

    switch(autoRoutine)
    {
        case AUTO_ROUTINE_ONE:
            routineOne();
            break;

        case AUTO_ROUTINE_TWO:
            routineTwo();
            break;

        case AUTO_ROUTINE_THREE:
            routineThree();
            break;

        case AUTO_ROUTINE_FOUR:
            routineFour();
            break;

        default:
            break;
    }
}
