#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     IR_Sensor,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          spinnerLeft,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          spinnerRight,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     linearRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     linearLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C2_1,    pullerLeft,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    pullerRight,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    doorFront,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_4,    doorBack,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Util.h"
#include "Motor.h"
#include "Auto.h"
#include "IR.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	disableDiagnosticsDisplay();

  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servoChangeRate[pullerLeft] = 2;
	servoChangeRate[pullerRight] = 3;



	nMotorEncoder[backRight] = 0;

	eraseDisplay();
  autoRoutine = selectAutoRoutine();

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

// Red - Ramp
// Start backwords
void  routineOne()
{
  eraseDisplay();
  nxtDisplayBigTextLine(0, "One");

  RetractGrabbers();


  /*
  // Our goal here is to grab a goal, then try and knock over a pole
  RetractGrabbers();		// Make sure the grabbers are up
  Drive(-64, 90); 		// Drive off the ramp
  wait1Msec(250);		// ----May need more stuff here to grab the goal----
  Drive(-28, 10);
  wait1Msec(500);
  StopDriveMotors();
  DeployGrabbers();		// Deploy the grabbers, hopefully grab a goal
  wait1Msec(2000);
  //Turn(-WHEEL_45_DEGREES, 90);  // Ideally turn 45* away from the wall
  //wait1Msec(250);
  //Drive(12, 90);		// ----TODO: Knock down the pole----
  //wait1Msec(250);
  */
};

// Red - Ground
void routineTwo()
{
  eraseDisplay();
  nxtDisplayBigTextLine(0, "Two");

  // Our goal here is to knock down the pole, then try and grab a bucket
  RetractGrabbers();
  Drive(5, 90);			// TODO: Have a real distance here
				// Drive a little away from the wall so we don't hit it when turning
  wait1Msec(250);
  Turn(WHEEL_90_DEGREES, 90);   // Turn 90* so our back will hit the pole
  wait1Msec(250);
  Turn(WHEEL_90_DEGREES, 90);
};

// Blue - Ramp
void routineThree()
{
	while (1)
	{
		eraseDisplay();
		nxtDisplayBigTextLine(0, "Three");

	//	Drive(70, 90);
	//	TurnLeft(45);
	}
};

// Blue - Ground
void routineFour()
{
	while (1)
	{
		eraseDisplay();
		nxtDisplayBigTextLine(0, "Four");

	//	Drive(25, 90);
	}
};

task main()
{
  initializeRobot();

  eraseDisplay();
  nxtDisplayBigTextLine(0, "Routine:");
  nxtDisplayBigTextLine(2, "%u", autoRoutine);

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  switch(autoRoutine)
	{
		case AUTO_ROUTINE_ONE:
			routineOne();
			break;
		case AUTO_ROUTINE_TWO:
			routineTwo();
			break;
		case AUTO_ROUTINE_THREE:
			routineThree();
			break;
		case AUTO_ROUTINE_FOUR:
			routineFour();
			break;
		default:
			break;
	}
}
