#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     IR_Sensor,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          spinnerLeft,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          spinnerRight,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     linearRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C2_1,    pullerLeft,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    pullerRight,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_3,    doorFront,            tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    doorBack,             tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Util.h"
#include "Motor.h"
#include "Controller.h"
#include "IR.h"

void initRobot()
{
	disableDiagnosticsDisplay();
	servoChangeRate[pullerLeft] = 2;
	servoChangeRate[pullerRight] = 3;

	startTask(Start_IR);

	nMotorEncoder[backRight] = 0;
}

task main()
{
	initRobot();

	waitForStart();

	while(1)
	{
		getJoystickSettings(joystick);

	  HandleDriveTrain(getRightJoyY(CONTROLLER_ONE), getRightJoyX(CONTROLLER_ONE));
	  HandleLinear(getLeftJoyY(CONTROLLER_ONE);
	  UpdateMotors();

		if (joy1Btn(CONTROLLER_BUTTON_A))
		{
	  	SpinSpinners();
		}

		if (joy1Btn(CONTROLLER_BUTTON_B))
		{
			StopSpinners();
		}

		if (joy1Btn(CONTROLLER_BUTTON_X))
		{
			servo[pullerLeft] = SERVO_LEFT_DOWN;
			servo[pullerRight] = SERVO_RIGHT_DOWN;
		}

		if (joy1Btn(CONTROLLER_BUTTON_Y))
		{
			// Up
			servo[pullerLeft] = SERVO_LEFT_UP;
			servo[pullerRight] = SERVO_RIGHT_UP;
		}

		if (joy2Btn(CONTROLLER_BUTTON_A))
		{
				servo[doorBack] = 125;
		}

			if (joy2Btn(CONTROLLER_BUTTON_B))
		{
			servo[doorBack] = 255;
		}

		if (joy2Btn(CONTROLLER_BUTTON_X))
		{
			servo[doorFront] = 60;
		}

		if (joy2Btn(CONTROLLER_BUTTON_Y))
		{
			servo[doorFront] = 255;
		}
	}
}
