#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          spinnerLeft,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          spinnerRight,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     linearLeftTop, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     linearLeftBot, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     linearRightTop, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     linearRightBot, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servoTest1,           tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoTest2,           tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Util.h"
#include "Motor.h"
#include "Auto.h"
#include "Controller.h"

void initRobot()
{
	//selectAutoRoutine();
}

void driverControlledPeriod()
{
	while(1)
	{
		getJoystickSettings(joystick);

		HandleDriveTrain(getRightJoyY(CONTROLLER_ONE), getRightJoyX(CONTROLLER_ONE));

		if (joy1Btn(CONTROLLER_BUTTON_B) == 1)
		{
			if (spinning)
			{
				StopSpinners();
			}
			else
			{
				SpinSpinners();
			}
		}
	}
}

void autoRoutinePeriod()
{

}

task main()
{
	initRobot();

	// TODO: Find out what this does
	//waitForStart();

	autoRoutinePeriod();

	driverControlledPeriod();
}
